'''
104: CRIE UM PROGRAMA QUE TENHA A FUNÇÃO LEAINT(), QUE VAI FUNCIONAR DE FORMA SEMELHANTE À FUNÇÃO INPUT() DO PYTHON. SÓ QUE FAZENDO A VALIDAÇÃO PARA ACEITAR APENAS UM VALOR NUMÉRICO.
EX:
N = LEIAINT('DIGITE UM N')
'''

