'''
LISTA DENTRO DE LISTAS

dados = ['pedro', 25]
dados2 = ['maria', 18]
pessoas = []
pessoas.append(dados[:])
pessoas.append(dados2[:])
pessoas = [['pedro, 25], ['maria', 18]]
print(pessoas[0][0]) --> pedro  (Primeiro é o índice do elemento da lista principal, depois é o índice da lista secundária que está dentro da principal)
print(pessoas[1]) --> Se eu não especificar a próxima posição ele vai me mostrar tudo


DESAFIOS:
084: FAÇA UM PROGRAMA QUE LEIA NOME E PESO DE VÁRIAS PESSOAS, GUARDANDP TUDO EM UMA LISTA. NO FINAL, MOSTRE:
A) QUANTAS PESSOAS FORAM CADASTRADAS
B) UMA LISTAGEM COM AS PESSOAS MAIS PESADAS
C) UMA LISTAGEM COM AS PESSOAS MAIS LEVES

085: CRIE UM PROGRAMA ONDE O USUÁRIO POSSA DIGITAR SETE VALORES NUMÉRICOS E CADASTRE-OS EM UMA LISTA ÚNICA QUE MANTENHA SEPARADOS OS VALORES PARES E ÍMPARES. NO FINAL, MOSTRE OS VALORES PARES E ÍMPARES EM ORDEM CRESCENTE.

086: CRIE UM PROGRAMA QUE CRIE UMA MATRIZ DE DIMENSÃO 3X3 E PREENCHA COM VALORES LIDOS PELO TECLADO
NO FINAL, MOSTRE A MATRIZ NA TELA, COM A FORMATAÇÃO CORRETA
EX:
1  2  3
4  5  6
7  8  8

087: APRIMORE O DESAFIO ANTERIOR, MOSTRANDO NO FINAL:
A) A SOMA DE TODOS OS VALORES PARES DIGITADOS
B) A SOMA DOS VALORES DA TERCEIRA COLUNA
C) O MAIOR VALOR DA SEGUNDA LINHA

088: FAÇA UM PROGRAMA QUE AJUDE UM JOGADOR DA MEGA SENA A CRIAR PALPITES. O PROGRAMA VAI PERGUNTAR QUANTOS JOGOS SERÃO GERADOS E VAI SORTEAR 6 NÚMEROS ENTRE 1 E 60 PARA CADA JOGO, CADASTRANDO TUDO EM UMA LISTA COMPOSTA

089: CRIE UM PROGRAMA QUE LEIA NOME E DUAS NOTAS DE VÁRIOS ALUNOS E GUARDE TUDO EM UM LISTA COMPOSTA. NO FINAL, MOSTRE UM BOLETIM CONTENDO A MÉDIA DE CADA UM E PERMITA QUE O USUÁRIO POSSA MOSTRAR AS NOTAS DE CADA ALUNO INDIVIDUALMENTE


'''